// Mock robusto de lugares reutilizable en todo el flujo.
// No importa si no es verídico: sirve para probar filtros, mapas y timeline.

import { Place } from "./itinerary-types";

export const MOCK_PLACES: Place[] = [
  {
    id: "p_palacio_bellasartes",
    name: "Palacio de Bellas Artes",
    state: "cdmx",
    category: ["arte", "historia", "museo"],
    coords: { lat: 19.4352, lng: -99.1412 },
    popularity: 98,
    avgStayMin: 75,
    tags: ["icono", "centro", "arquitectura"],
  },
  {
    id: "p_castillo_chapultepec",
    name: "Castillo de Chapultepec",
    state: "cdmx",
    category: ["historia", "museo", "mirador"],
    coords: { lat: 19.4204, lng: -99.1819 },
    popularity: 96,
    avgStayMin: 90,
    tags: ["bosque", "vista"],
  },
  {
    id: "p_museo_antropologia",
    name: "Museo Nacional de Antropología",
    state: "cdmx",
    category: ["museo", "historia", "arte"],
    coords: { lat: 19.426, lng: -99.186 },
    popularity: 99,
    avgStayMin: 120,
  },
  {
    id: "p_piramides_teotihuacan",
    name: "Zonas Arqueológicas de Teotihuacán",
    state: "edomex",
    category: ["historia", "naturaleza", "mirador"],
    coords: { lat: 19.6925, lng: -98.843 },
    popularity: 95,
    avgStayMin: 160,
  },
  {
    id: "p_huasca_duendes",
    name: "Bosque de los Duendes · Huasca",
    state: "hidalgo",
    category: ["naturaleza", "parque"],
    coords: { lat: 20.203, lng: -98.57 },
    popularity: 78,
    avgStayMin: 80,
  },
  {
    id: "p_peña_bernal",
    name: "Peña de Bernal",
    state: "queretaro",
    category: ["naturaleza", "mirador"],
    coords: { lat: 20.741, lng: -99.944 },
    popularity: 92,
    avgStayMin: 90,
  },
  {
    id: "p_tepoztlan_centro",
    name: "Tepoztlán Centro",
    state: "morelos",
    category: ["naturaleza", "shopping", "gastronomia"],
    coords: { lat: 18.986, lng: -99.096 },
    popularity: 89,
    avgStayMin: 120,
  },
  {
    id: "p_frida_casa_azul",
    name: "Museo Frida Kahlo · Casa Azul",
    state: "cdmx",
    category: ["museo", "arte", "historia"],
    coords: { lat: 19.355, lng: -99.162 },
    popularity: 97,
    avgStayMin: 70,
  },
  {
    id: "p_alameda_qro",
    name: "Alameda Hidalgo · Querétaro",
    state: "queretaro",
    category: ["parque", "naturaleza"],
    coords: { lat: 20.588, lng: -100.39 },
    popularity: 74,
    avgStayMin: 60,
  },
  {
    id: "p_tacos_noche",
    name: "Taquitos de Noche (spot popular)",
    state: "cdmx",
    category: ["gastronomia", "noche"],
    coords: { lat: 19.43, lng: -99.16 },
    popularity: 88,
    avgStayMin: 40,
  },
];
